<?php

/**
 * Akkar Global Services - Diagnostics Workshops Seeder
 *
 * @author Julio Hernandez <juliohernandezs@gmail.com>
 *
 * @date(April 17 - 2017)
 */

use App\Diagnostic;
use App\DiagnosticState;
use App\State;
use Illuminate\Database\Seeder;

class DiagnosticsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $diagnostics = [
            ["code" => "accesory_from_a_different_brand", 
                "name_es" => "ACCESORIO NO ORIGINAL", "name_en" => "ACCESORY FROM A DIFFERENT BRAND",
                "states" => ["cannot_be_repaired"],
            ],
            ["code" => "physical_damage", 
                "name_es" => "DAÑO FISICO", "name_en" => "PHYSICAL DAMAGE",
                "states" => ["cannot_be_repaired"],
            ],
            ["code" => "document_inconsistency", 
                "name_es" => "INCONSISTENCIA DE DOCUMENTOS", "name_en" => "DOCUMENT INCONSISTENCY",
                "states" => ["cannot_be_repaired"],
            ],
            ["code" => "requires_antenna", 
                "name_es" => "REQUIERE ANTENA", "name_en" => "REQUIRES ANTENNA",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_earphones", 
                "name_es" => "REQUIERE AUDIFONOS", "name_en" => "REQUIRES EARPHONES",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_earpiece", 
                "name_es" => "REQUIERE AURICULAR", "name_en" => "REQUIRES EARPIECE",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_battery", 
                "name_es" => "REQUIERE BATERIA", "name_en" => "REQUIRES BATTERY",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_power_button", 
                "name_es" => "REQUIERE BOTON DE ENCENDIDO", "name_en" => "REQUIRES POWER BUTTON",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_volume_button", 
                "name_es" => "REQUIERE BOTON DE VOLUMEN", "name_en" => "REQUIRES VOLUME BUTTON",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_usb_cable", 
                "name_es" => "REQUIERE CABLE USB", "name_en" => "REQUIRES USB CABLE",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_camera", 
                "name_es" => "REQUIERE CAMARA", "name_en" => "REQUIRES CAMERA",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_charger", 
                "name_es" => "REQUIERE CARGADOR", "name_en" => "REQUIRES CHARGER",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_charging_connector", 
                "name_es" => "REQUIERE CONECTOR DE CARGA", "name_en" => "REQUIRES CHARGING CONNECTOR",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_speaker", 
                "name_es" => "REQUIERE CORNETA", "name_en" => "REQUIRES SPEAKER",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_earphone_jack", 
                "name_es" => "REQUIERE ENTRADA DE AUDIFONOS", "name_en" => "REQUIRES EARPHONE JACK",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_flash", 
                "name_es" => "REQUIERE FLASH", "name_en" => "REQUIRES FLASH",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_led", 
                "name_es" => "REQUIERE LED", "name_en" => "REQUIRES LED",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_flashlight", 
                "name_es" => "REQUIERE LINTERNA", "name_en" => "REQUIRES FLASHLIGHT",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_microphone", 
                "name_es" => "REQUIERE MICROFONO", "name_en" => "REQUIRES MICROPHONE",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_lcd_screen", 
                "name_es" => "REQUIERE PANTALLA LCD", "name_en" => "REQUIRES LCD SCREEN",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_lcd_and_touch_screens", 
                "name_es" => "REQUIERE PANTALLA LCD Y TACTIL", "name_en" => "REQUIRES LCD AND TOUCH SCREENS",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_touch_screen", 
                "name_es" => "REQUIERE PANTALLA TACTIL", "name_en" => "REQUIRES TOUCH SCREEN",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_sim_port", 
                "name_es" => "REQUIERE PUERTO SIM CARD", "name_en" => "REQUIRES SIM PORT",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_micro_sd_port", 
                "name_es" => "REQUIERE PUERTO TARJETA SD", "name_en" => "REQUIRES MICRO SD PORT",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_proximity_sensor", 
                "name_es" => "REQUIERE SENSOR DE PROXIMIDAD", "name_en" => "REQUIRES PROXIMITY SENSOR",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_pcba", 
                "name_es" => "REQUIERE TARJETA LOGICA", "name_en" => "REQUIRES PCBA",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_keyboard", 
                "name_es" => "REQUIERE TECLADO", "name_en" => "REQUIRES KEYBOARD",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "requires_vibrator", 
                "name_es" => "REQUIERE VIBRADOR", "name_en" => "REQUIRES VIBRATOR",
                "states" => ["spare_part_not_available", "cannot_be_repaired", "pending_client_approval"],
            ],
            ["code" => "water_label_activated", 
                "name_es" => "SENSOR DE HUMEDAD ACTIVADO", "name_en" => "WATER LABEL ACTIVATED",
                "states" => ["cannot_be_repaired"],
            ],
            ["code" => "unit_has_been_opened", 
                "name_es" => "UNIDAD FUE ABIERTA", "name_en" => "UNIT HAS BEEN OPENED",
                "states" => ["cannot_be_repaired"],
            ],
            ["code" => "antenna_failure", 
                "name_es" => "FALLA ANTENA", "name_en" => "ANTENNA FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "earphones_failure", 
                "name_es" => "FALLA AUDIFONOS", "name_en" => "EARPHONES FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "earpiece_failure", 
                "name_es" => "FALLA AURICULAR", "name_en" => "EARPIECE FAILURER",
                "states" => ["repaired"],
            ],
            ["code" => "battery_failure", 
                "name_es" => "FALLA BATERIA", "name_en" => "BATTERY FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "power_button_failure", 
                "name_es" => "FALLA BOTON DE ENCENDIDO", "name_en" => "POWER BUTTON FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "volume_button_failure", 
                "name_es" => "FALLA BOTON DE VOLUMEN", "name_en" => "VOLUME BUTTON FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "usb cable_failure", 
                "name_es" => "FALLA CABLE USB", "name_en" => "USB CABLE FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "camera_failure", 
                "name_es" => "FALLA CAMARA", "name_en" => "CAMERA FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "charger_failure", 
                "name_es" => "FALLA CARGADOR", "name_en" => "CHARGER FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "charging_connector_failure", 
                "name_es" => "FALLA CONECTOR DE CARGA", "name_en" => "CHARGING CONNECTOR FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "speaker_failure", 
                "name_es" => "FALLA CORNETA", "name_en" => "SPEAKER FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "earphone_jack_failure", 
                "name_es" => "FALLA ENTRADA DE AUDIFONOS", "name_en" => "EARPHONE JACK FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "flash_failure", 
                "name_es" => "FALLA FLASH", "name_en" => "FLASH FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "led_failure", 
                "name_es" => "FALLA LED", "name_en" => "LED FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "flashlight_failure", 
                "name_es" => "FALLA LINTERNA", "name_en" => "FLASHLIGHT FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "microphone_failure", 
                "name_es" => "FALLA MICROFONO", "name_en" => "MICROPHONE FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "lcd_screen_failure", 
                "name_es" => "FALLA PANTALLA LCD", "name_en" => "LCD SCREEN FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "lcd_and_touch_screens_failure", 
                "name_es" => "FALLA PANTALLA LCD Y TACTIL", "name_en" => "LCD AND TOUCH SCREENS FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "touch_screen_failure", 
                "name_es" => "FALLA PANTALLA TACTIL", "name_en" => "TOUCH SCREEN FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "sim_port_failure", 
                "name_es" => "FALLA PUERTO SIM CARD", "name_en" => "SIM PORT FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "micro_sd_port_failure", 
                "name_es" => "FALLA PUERTO TARJETA SD", "name_en" => "MICRO SD PORT FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "proximity_sensor_failure", 
                "name_es" => "FALLA SENSOR DE PROXIMIDAD", "name_en" => "PROXIMITY SENSOR FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "pcba_failure", 
                "name_es" => "FALLA TARJETA LOGICA", "name_en" => "PCBA FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "keyboard_failure", 
                "name_es" => "FALLA TECLADO", "name_en" => "KEYBOARD FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "vibrator_failure", 
                "name_es" => "FALLA VIBRADOR", "name_en" => "VIBRATOR FAILURE",
                "states" => ["repaired"],
            ],
            ["code" => "software_failure", 
                "name_es" => "FALLA DE SOFTWARE", "name_en" => "SOFTWARE FAILURE",
                "states" => ["repaired"],
            ],
        ];

        foreach ($diagnostics as $item) {
            $diagnostic = Diagnostic::create([
                'code' => $item['code'],
                'en'  => ['name' => $item['name_en']],
                'es'  => ['name' => $item['name_es']]
            ]);

            foreach ($item['states'] as $key => $value) {
                $state = State::where('code', $value)->select('id')->first();
                if ($state){
                    DiagnosticState::create([
                        'diagnostic_id' => $diagnostic->id,
                        'state_id' => $state->id,
                    ]);
                }
            }
        }
    }
}
